/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class TransactionFrame extends javax.swing.JFrame {
private javax.swing.JTextField txtSearchID;
private javax.swing.JButton btnSearch;
    /**
     * Creates new form TransactionFrame
     */
    public TransactionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtSearchID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton("Search");
    }
// Paste these at the very top of your class, above the constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchId = new javax.swing.JTextField();
        lblBalance = new javax.swing.JLabel();
        btnSearchID = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtSearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIdActionPerformed(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBalance.setText("BALANCE:");

        btnSearchID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchID.setText("SEARCH");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });

        btnDeposit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeposit.setText("DEPOSIT");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnWithdraw.setText("WITHDRAW");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Trans ID", "Account ID", "Type", "Amount", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTransactions);
        if (tblTransactions.getColumnModel().getColumnCount() > 0) {
            tblTransactions.getColumnModel().getColumn(0).setResizable(false);
            tblTransactions.getColumnModel().getColumn(1).setResizable(false);
            tblTransactions.getColumnModel().getColumn(2).setResizable(false);
            tblTransactions.getColumnModel().getColumn(3).setResizable(false);
            tblTransactions.getColumnModel().getColumn(4).setResizable(false);
        }

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblName.setText("CUSTOMER NAME:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("TRANSACTION WINDOW");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("CUSTOMER ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("AMOUNT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchID))
                    .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeposit)
                        .addGap(18, 18, 18)
                        .addComponent(btnWithdraw)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchID)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(lblBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw)
                    .addComponent(btnDeposit)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
   lblBalance.setText(""); 
    String customerId = txtSearchId.getText();

    if (customerId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Account ID.");
        return;
    }

    try {
        refreshBalance();
        searchTransactions(customerId);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
   String customerId = txtSearchId.getText().trim();
        if (customerId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Customer ID first!");
            return;
        }

        String amountInput = txtAmount.getText().trim();
        if (amountInput.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an amount to deposit!");
            return;
        }

        try {
            double amount = Double.parseDouble(amountInput);
            
            try (java.sql.Connection conn = DatabaseConnection.getConnection()) {
                // 1. Find the Account ID linked to this Customer ID
                String findAccSql = "SELECT account_id FROM accounts WHERE customer_id = ?";
                java.sql.PreparedStatement pstmtFind = conn.prepareStatement(findAccSql);
                pstmtFind.setString(1, customerId);
                java.sql.ResultSet rs = pstmtFind.executeQuery();
                
                if (rs.next()) {
                    int accountId = rs.getInt("account_id");
                    
                    // 2. Add money to balance using the CORRECT Account ID
                    String sqlUpdate = "UPDATE accounts SET balance = balance + ? WHERE account_id = ?";
                    java.sql.PreparedStatement pstmtUpdate = conn.prepareStatement(sqlUpdate);
                    pstmtUpdate.setDouble(1, amount);
                    pstmtUpdate.setInt(2, accountId);
                    pstmtUpdate.executeUpdate();
                    
                    // 3. Log transaction
                    String sqlLog = "INSERT INTO transactions (account_id, transaction_type, amount) VALUES (?, 'Deposit', ?)";
                    java.sql.PreparedStatement pstmtLog = conn.prepareStatement(sqlLog);
                    pstmtLog.setInt(1, accountId);
                    pstmtLog.setDouble(2, amount);
                    pstmtLog.executeUpdate();
                    
                    javax.swing.JOptionPane.showMessageDialog(this, "Deposit Successful!");
                    refreshBalance();
                    searchTransactions(customerId);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "No account found for this Customer ID!");
                }
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid number format.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed

    String customerId = txtSearchId.getText().trim();
        if (customerId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Customer ID first!");
            return;
        }

        try {
            double amount = Double.parseDouble(txtAmount.getText().trim());
            
            try (java.sql.Connection conn = DatabaseConnection.getConnection()) {
                // 1. Find the Account ID and current balance for this customer
                String sqlCheck = "SELECT account_id, balance FROM accounts WHERE customer_id = ?";
                java.sql.PreparedStatement pstmtCheck = conn.prepareStatement(sqlCheck);
                pstmtCheck.setString(1, customerId);
                java.sql.ResultSet rs = pstmtCheck.executeQuery();
                
                if (rs.next()) {
                    int accountId = rs.getInt("account_id");
                    double currentBalance = rs.getDouble("balance");
                    
                    if (currentBalance >= amount) {
                        // 2. Update balance using CORRECT Account ID
                        String sqlUpdate = "UPDATE accounts SET balance = balance - ? WHERE account_id = ?";
                        java.sql.PreparedStatement pstmtUpdate = conn.prepareStatement(sqlUpdate);
                        pstmtUpdate.setDouble(1, amount);
                        pstmtUpdate.setInt(2, accountId);
                        pstmtUpdate.executeUpdate();
                        
                        // 3. Log transaction
                        String sqlLog = "INSERT INTO transactions (account_id, transaction_type, amount) VALUES (?, 'Withdraw', ?)";
                        java.sql.PreparedStatement pstmtLog = conn.prepareStatement(sqlLog);
                        pstmtLog.setInt(1, accountId);
                        pstmtLog.setDouble(2, amount);
                        pstmtLog.executeUpdate();
                        
                        javax.swing.JOptionPane.showMessageDialog(this, "Withdrawal Successful!");
                        refreshBalance();
                        searchTransactions(customerId);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Insufficient Funds!");
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Account not found for this Customer ID!");
                }
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number");
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void txtSearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblTransactions;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtSearchId;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void refreshBalance() {
     String customerId = txtSearchId.getText().trim();
        if (customerId.isEmpty()) return;

        try (java.sql.Connection conn = DatabaseConnection.getConnection()) {
         
            String sql = "SELECT a.balance, c.first_name, c.last_name " +
                         "FROM accounts a " +
                         "JOIN customers c ON a.customer_id = c.customer_id " +
                         "WHERE a.customer_id = ?";
                         
            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, customerId);
            java.sql.ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
              
                double balance = rs.getDouble("balance");
                String firstName = rs.getString("first_name");
                String lastName = rs.getString("last_name");
                
                // 3. Update both of your labels!
                lblBalance.setText("Balance: $" + String.format("%.2f", balance));
                lblName.setText("Customer: " + firstName + " " + lastName); 
            } else {
              
                lblBalance.setText("Account not found");
                lblName.setText(""); 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
private void searchTransactions(String customerId) {
       
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblTransactions.getModel();
     
        
        
        model.setRowCount(0);

        String query = "SELECT t.* FROM transactions t " +
                       "JOIN accounts a ON t.account_id = a.account_id " +
                       "WHERE a.customer_id = ?";

        try (java.sql.Connection conn = DatabaseConnection.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setString(1, customerId);
            java.sql.ResultSet rs = pstmt.executeQuery();
            
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("transaction_id"), 
                    rs.getInt("account_id"), 
                    rs.getString("transaction_type"), 
                    rs.getDouble("amount"), 
                    rs.getTimestamp("transaction_date")
                });
            }
            
        } catch (Exception e) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Error updating table: " + e.getMessage());
        }
    }

}


